services:
  dash:
    build: .
    image: dash:latest
    container_name: dash
    ports:
      - "8050:8050"

    volumes:
      - "/etc/localtime:/etc/localtime:ro" 
      - "/etc/timezone:/etc/timezone:ro" 
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN} 

